name: lens_new
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  animations: ^2.0.7
  bitsdojo_window: ^0.1.5
  dropdown_button2: ^1.9.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.2.0
  get: 4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  just_the_tooltip: ^0.0.12
  mockito: ^5.3.2
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

  integration_test:
    sdk: flutter
  isar_generator: ^3.0.5

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
